collector:
  kafka:
    producer:
      properties:
        "bootstrap.servers": localhost:9092
        "value.serializer": serializer.EventSerializer
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        "batch.size": 10000
        "linger.ms": 2000
      topics:
        snapshots: telemetry.snapshots.v1
      timeUntilClosingMs: 5000
    consumer:
      properties:
        "bootstrap.servers": localhost:9092
        "client.id": Consumer-1
        "group.id": some.group.id
        "value.deserializer": deserializer.SensorEventDeserializer
        "max.poll.records": 100
        "fetch.max.bytes": 3072000
        "enable.auto.commit": false
      topics:
        snapshots: telemetry.snapshots.v1
        sensors_events: telemetry.sensors.v1
      consumeAttemptTimeout: 10000